export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCESS = "USER_SIGNIN_SUCESS";
export const USER_SIGNIN_FAILED = "USER_SIGNIN_FAILED";
export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCESS = "USER_SIGNUP_SUCESS"
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED"