export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const SHIPPING_ADDRESS_SAVE = "SHIPPING_ADDRESS_SAVE";

export const SAVE_PAYMENY_METHOD = "SAVE_PAYMENT_METHOD";

export const CART_EMPTY = "CART_EMPTY"
